version: "2"
services:
  web:
    build: ./docker/web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www

  app:
    build:
      context: ./docker/app
    environment:
      DB_HOST: db
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/var/www
      - ./docker/app/php-fpm.conf:/usr/local/etc/php/php-fpm.conf
      - ./.env:/var/www/config.env

  db:
    build: ./docker/db
    env_file: .env
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d

# database のように永続的なストレージが欲しい場合に必要な
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  db-data:
    driver: local
