version: "2"
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../html:/var/www/html

  app:
    build:
      context: ./app
    env_file: ../.env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - ../html:/var/www/html
      - ./app/php-fpm.conf:/usr/local/etc/php/php-fpm.conf

  db:
    image: mysql:latest
    env_file: ../.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

# database のように永続的なストレージが欲しい場合に必要な
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  db-data:
    driver: local
